// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQz6yoE5dyLDFCDEpMhaNvO6Oycg-mzU',
    appId: '1:856077968429:web:aa09dce17946d9f46f84a4',
    messagingSenderId: '856077968429',
    projectId: 'shopping-app-hong',
    authDomain: 'shopping-app-hong.firebaseapp.com',
    storageBucket: 'shopping-app-hong.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkOw_k-dJDEFtNZjQsJPrq1dUgiGCBus4',
    appId: '1:856077968429:android:ee610fe3e055d2c16f84a4',
    messagingSenderId: '856077968429',
    projectId: 'shopping-app-hong',
    storageBucket: 'shopping-app-hong.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABxq5kKm1mPLkKB_4f-tIFKmM1zapQSnE',
    appId: '1:856077968429:ios:5b11c534dbf92ecc6f84a4',
    messagingSenderId: '856077968429',
    projectId: 'shopping-app-hong',
    storageBucket: 'shopping-app-hong.appspot.com',
    iosClientId: '856077968429-qg3dov02pael4ipf5ikjbd9afeppomm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABxq5kKm1mPLkKB_4f-tIFKmM1zapQSnE',
    appId: '1:856077968429:ios:2123d7d0737296936f84a4',
    messagingSenderId: '856077968429',
    projectId: 'shopping-app-hong',
    storageBucket: 'shopping-app-hong.appspot.com',
    iosClientId: '856077968429-h61kkloa8puhtbet0s0bghp05famcpu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
